const char* glsl_basic_vs = "#version 460 core\n"
    "layout (location = 0) in vec3 aPos;\n"
    "layout (location = 1) in vec3 aColor;\n"
    "out vec3 out_color;\n"
    "uniform mat4 model;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "void main()\n"
    "{\n"
    "   gl_Position = projection * view * model * vec4(aPos.x, aPos.y, aPos.z, 1.0);\n"
    "   out_color = aColor;\n"
    "}\0";

const char* glsl_basic_fs = "#version 460 core\n"
    "in vec3 out_color;\n" // input from vertex (in n out must match)
    "out vec4 final_color;\n"
    "void main()\n"
    "{\n"
    "   final_color = vec4(out_color, 1.0);\n"
    "}\0";

const char* glsl_font_vs = "#version 460 core\n"
    "layout (location = 0) in vec2 aPos;\n"
    "layout (location = 1) in vec2 aTex;\n"
    "out vec2 pass_texture_uv;\n"
    "void main()\n"
    "{\n"
    "   gl_Position = vec4(aPos, 0.0, 1.0);\n"
    "   pass_texture_uv = aTex;\n"
    "}\0";

const char* glsl_font_fs = "#version 460 core\n"
    "in vec2 pass_texture_uv;\n"              
    "uniform sampler2D textureSampler;\n"     
    "out vec4 final_color;\n"
    "void main()\n"
    "{\n"
    "   final_color = texture(textureSampler, pass_texture_uv);\n"
    "}\0";

const char* glsl_cube_vs = "#version 460 core\n"
    "layout (location = 0) in vec3 aPos;\n"
    "layout (location = 1) in vec3 aNorm;\n"
    "layout (location = 2) in vec2 aTex;\n"
    "uniform mat4 model;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "uniform vec4 color;\n"
    "out vec2 pass_texture_uv;\n"
    "out vec4 pass_color;\n"
    "void main()\n"
    "{\n"
    "   gl_Position = projection * view * model * vec4(aPos, 1.0);\n"
    "   pass_texture_uv = aTex;\n"
    "   pass_color = color;\n"
    "}\0";

const char* glsl_cube_fs = "#version 460 core\n"
    "in vec2 pass_texture_uv;\n"              
    "in vec4 pass_color;\n"
    "uniform sampler2D textureSampler;\n"     
    "out vec4 final_color;\n"
    "void main()\n"
    "{\n"
    "   final_color = texture(textureSampler, pass_texture_uv) * pass_color;\n"
    "}\0";

const char* glsl_teapot_vs = "#version 460 core\n"
    "layout (location = 0) in vec3 aPos;\n"
    "uniform mat4 model;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "uniform vec4 color;\n"
    "out vec4 pass_color;\n"
    "void main()\n"
    "{\n"
    "   gl_Position = projection * view * model * vec4(aPos.x, aPos.y, aPos.z, 1.0);\n"
    "   pass_color = color;\n"
    "}\0";

const char* glsl_teapot_fs = "#version 460 core\n"
    "out vec4 final_color;\n"
    "in vec4 pass_color;\n"
    "void main()\n"
    "{\n"
    "   final_color = pass_color;\n"
    "}\0";
// 0.5, 0.8, 0.2, 1.0 // cool green
const char* glsl_skybox_vs = "#version 460 core\n"
    "layout (location = 0) in vec3 aPos;\n"
    "out vec3 TexCoords;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "void main()\n"
    "{\n"
    "   TexCoords = aPos;\n"
    "   gl_Position = projection * view * vec4(aPos, 1.0);\n"
    "}\0";

const char* glsl_skybox_fs = "#version 460 core\n"
    "out vec4 FragColor;\n"
    "in vec3 TexCoords;\n"
    "uniform samplerCube skybox;\n"
    "void main() {\n"
    "    FragColor = texture(skybox, TexCoords);\n"
    "}\n";


const char* glsl_instanced_vs = "#version 460 core\n"
    "layout (location = 0) in vec3 aPos;\n"
    "layout (location = 1) in vec2 aTexCoord;\n"
    "out vec2 TexCoord;\n"
    "uniform mat4 model;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "uniform vec3 offsets[1600];\n"
    "void main()\n"
    "{\n"
    "   vec3 offset = offsets[gl_InstanceID];\n"
    "   vec4 transformed = model * vec4(aPos, 1.0);\n"
    "   gl_Position = projection * view * vec4(transformed.xyz + offset, 1.0);\n"
    "   TexCoord = aTexCoord;\n"
    "}\0";

const char* glsl_instanced_fs = "#version 460 core\n"
    "out vec4 final_color;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D Texture;\n"
    "void main()\n"
    "{\n"
    "   final_color = texture(Texture, TexCoord);\n"
    "}\0";
