const char* vertex_shader_basic_src = "#version 460 core\n"
    "layout (location = 0) in vec3 aPos;\n"
    "uniform mat4 model;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "void main()\n"
    "{\n"
    "   gl_Position = projection * view * model * vec4(aPos.x, aPos.y, aPos.z, 1.0);\n"
    "}\0";

const char* fragment_shader_basic_src = "#version 460 core\n"
    "out vec4 final_color;\n"
    "void main()\n"
    "{\n"
    "   final_color = vec4(1.0, 0.0, 0.0, 1.0);\n"
    "}\0";

const char* vertex_shader_instance_src = "#version 460 core\n"
    "layout (location = 0) in vec3 aPos;\n"
    "layout (location = 1) in vec2 aTexCoord;\n"
    "out vec2 TexCoord;\n"
    "uniform mat4 model;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "uniform vec3 offsets[1600];\n"
    "void main()\n"
    "{\n"
    "   vec3 offset = offsets[gl_InstanceID];\n"
    "   vec4 transformed = model * vec4(aPos, 1.0);\n"
    "   gl_Position = projection * view * vec4(transformed.xyz + offset, 1.0);\n"
    "   TexCoord = aTexCoord;\n"
    "}\0";

const char* fragment_shader_src = "#version 460 core\n"
    "out vec4 final_color;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D Texture;\n"
    "void main()\n"
    "{\n"
    "   final_color = texture(Texture, TexCoord);\n"
    "}\0";
